# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: true
  branches:
    include:
    - master

pr:
- master

schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    npm install
    tsc --target ES6 --strict true --project tsconfig.json --sourcemap
    npm run build
  displayName: 'ts compile. npm package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build'
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'web-app-sample'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'