trigger:
  batch: true
  branches:
    include:
    - master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

pr:
- master

schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - master

stages:
- stage: BuildAndPush
  display: build and push
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'rhythmcollective/web-app-sample'
        command: 'buildAndPush'
        Dockerfile: 'docker/prod.dockerfile'
        tags: |
              $(tag)
              'latest'
