trigger:
  batch: true
  branches:
    include:
    - master

pr:
- master

schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- script: |
    npm install
    tsc --target ES6 --strict true --project tsconfig.json --sourcemap
    npm run build
  displayName: 'ts compile. npm package'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'helm/webapp-production.yaml'
    artifactName: 'helm-chart'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'rhythmcollective/web-app-sample'
    command: 'buildAndPush'
    Dockerfile: 'docker/prod.dockerfile'
