trigger:
  batch: true
  branches:
    include:
    - master

pr:
- master

schedules:
- cron: "0 0 * * *"
  displayName: Daily
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'rhythmcollective/web-app-sample'
    command: 'buildAndPush'
    Dockerfile: 'docker/prod.dockerfile'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build'
    artifactName: 'build'
